#docker compose
version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq-wjr
    #container_name: rabbitmq
    volumes:      
      #- ./rabbitmq/etc/:/etc/rabbitmq/
      #- ./rabbitmq/data/:/var/lib/rabbitmq/
      #- ./rabbitmq/logs/:/var/log/rabbitmq/
      #- ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      #- ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-wjr
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
  webApi31:
    image: webapi31
    ports:
      - "8000:8080"
    depends_on:
      - "rabbitmq"
  webApi50:
    image: webapi50
    ports:
      - "8002:8080"
    depends_on:
      - "rabbitmq"